import { jsPDF } from 'jspdf';
import { Patient } from '@/contexts/DataContext';

export function exportCarePlanPDF(patient: Patient) {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  doc.setFontSize(20);
  doc.setTextColor(14, 165, 233);
  doc.text('CareContext', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Adapted Care Plan Report', margin, y);
  y += 15;

  doc.setDrawColor(14, 165, 233);
  doc.line(margin, y, 190, y);
  y += 10;

  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text(`Patient: ${patient.name}`, margin, y);
  y += 7;

  doc.setFontSize(11);
  doc.text(`Age: ${patient.age || 'N/A'}  |  Condition: ${patient.condition || 'N/A'}`, margin, y);
  y += 7;
  doc.text(`Medications: ${patient.medications || 'N/A'}`, margin, y);
  y += 12;

  doc.setFontSize(12);
  doc.setTextColor(14, 165, 233);
  doc.text('Life Context Summary', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  const lc = patient.lifeContext;
  const contextItems = [
    `Work Schedule: ${lc.workSchedule}`,
    `Commute: ${lc.commuteTime}`,
    `Food Access: ${lc.foodAccess}`,
    `Sleep: ${lc.sleepHours}`,
    `Stress Level: ${lc.stressLevel}`,
    `Living Situation: ${lc.livingSituation}`,
  ];
  contextItems.forEach(item => {
    doc.text(`• ${item}`, margin + 4, y);
    y += 6;
  });
  y += 6;

  if (patient.conflictFlags.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(245, 158, 11);
    doc.text('Conflict Flags', margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    patient.conflictFlags.forEach(flag => {
      const lines = doc.splitTextToSize(flag, 160);
      doc.text(lines, margin + 4, y);
      y += lines.length * 6;
    });
    y += 6;
  }

  if (patient.adaptedCarePlan) {
    doc.setFontSize(12);
    doc.setTextColor(16, 185, 129);
    doc.text('Adapted Care Plan', margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    const planLines = doc.splitTextToSize(patient.adaptedCarePlan, 165);
    planLines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin + 4, y);
      y += 5.5;
    });
  }

  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by CareContext on ${new Date().toLocaleDateString()}`, margin, 285);

  doc.save(`CareContext_${patient.name.replace(/\s/g, '_')}_CarePlan.pdf`);
}
